tasks:
    - name: Nextflow Install
      init: |
            curl -s https://get.nextflow.io | bash
            chmod +x nextflow
            sudo mv /workspace/scRNAmazed/nextflow /usr/local/bin
            nextflow info
            clear
      command: exit
    - name: Conda Install
      init: |
            mkdir -p ~/miniconda3
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
            bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
            rm -rf ~/miniconda3/miniconda.sh
            ~/miniconda3/bin/conda init bash
            ~/miniconda3/bin/conda init zsh
            gp sync-done conda
      command: exit          
    - name: Main Terminal
      init: |
            clear
            echo "Please wait until the other terminal are done with the setup of the environment"
            echo "Then run the following 3 lines in a new terminal"
            echo "conda env create -f CONDA_ENVS/r_env.yml"
            echo "conda env create -f CONDA_ENVS/py_env.yml"
            echo 'export CONDA_ENVS_PATH="`conda info --base`/envs"'
            echo "Loading..."
            gp sync-await conda
            echo "All done, you can now open a new terminal and run the 3 lines"
            