tasks:
    - name: Nextflow Install
      init: |
            curl -s https://get.nextflow.io | bash
            chmod +x nextflow
            sudo mv /workspace/scRNAmazed/nextflow /usr/local/bin
            nextflow info
            clear
      command: exit
    - name: Conda Install & Environments Setup
      init: |
            mkdir -p ~/miniconda3
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
            bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
            rm -rf ~/miniconda3/miniconda.sh
            ~/miniconda3/bin/conda init bash
            ~/miniconda3/bin/conda init zsh
            gp sync-done conda
            source ~/.bashrc
            conda env create --yes -f CONDA_ENVS/py_env.yml
            conda env create --yes -f CONDA_ENVS/r_env.yml
            conda env create --yes -f CONDA_ENVS/enrichment_env.yml
            ln -s "`conda info --base`/envs/py_env" CONDA_ENVS/
            ln -s "`conda info --base`/envs/r_env" CONDA_ENVS/
            ln -s "`conda info --base`/envs/enrichment_env" CONDA_ENVS/
            gp sync-done env

      command: exit      
    - name: Main Terminal
      init: |
            clear
            echo "Please wait until the other terminal are done with the setup of the environment"
            echo "Downloading Conda..."
            gp sync-await conda
            echo "Downloading Environments... (this may take a while)"
            gp sync-await env
            source ~/.bashrc
            echo "All done, you can now run the following line and enjoy the pipeline:"
            echo "nextflow run main.nf"
            