tasks:
    - name: Nextflow Install
      init: |
            curl -s https://get.nextflow.io | bash
            chmod +x nextflow
            sudo mv /workspace/scRNAmazed/nextflow /usr/local/bin
            nextflow info
            clear
      command: exit
    - name: Conda install
      init: |
            mkdir -p ~/miniconda3
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
            bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
            rm -rf ~/miniconda3/miniconda.sh
            ~/miniconda3/bin/conda init bash
            ~/miniconda3/bin/conda init zsh
    - name: Main Terminal
      init: |
            clear
            echo "Here are the instructions"
            echo "But they are none for now (*＞ω＜*)♡"
            echo "You can copy-paste this tho"
            echo "nextflow run main.nf"